// <auto-generated />
using EFCoreAnima;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreAnima.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250411114849_NullableAnimalsAttributes")]
    partial class NullableAnimalsAttributes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("EFCoreAnima.Classes.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colour")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("TierheimId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TierheimId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("EFCoreAnima.Classes.Tierheim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TierheimName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tierheime");
                });

            modelBuilder.Entity("EFCoreAnima.Classes.Animal", b =>
                {
                    b.HasOne("EFCoreAnima.Classes.Tierheim", "Tierheim")
                        .WithMany("AnimalsList")
                        .HasForeignKey("TierheimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tierheim");
                });

            modelBuilder.Entity("EFCoreAnima.Classes.Tierheim", b =>
                {
                    b.Navigation("AnimalsList");
                });
#pragma warning restore 612, 618
        }
    }
}
